### ISSUE TITLE
Code is not in sync with Plural sight video

### ISSUE THREAD

**Issue by rajurh** [KevinDockx/RESTfulAPIAspNetCore_Course#1]
Code doesn't consists of controllers, Automapper changes etc Can those changes will be published?

**Comment by KevinDockx** [comment]
Hi,

this repo contains the starter files for the course, so you can follow along.  If you want the finished code, you can download that from the "Exercises" tab on the course page at Pluralsight.

**Comment by zsxawerdu** [comment]
thanks for your work kevin.
