### ISSUE TITLE
remaining code

### ISSUE THREAD

**Issue by nyghtrocker** [KevinDockx/RESTfulAPIAspNetCore_Course#2]
Hi, This course is really awesome. Please update the remaning code. I will be very greatful to you.

**Comment by ghost** [comment]
Code ain't working on vs2017

**Comment by EvgenySerg** [comment]
Could you Update it to Net Core version 2.1?
It does not work. Migrations does not work.

**Comment by RobertCekay** [comment]
Please Update or remove from pluralsight

**Comment by willvelida** [comment]
I've created a PR that includes the starter projects for all versions: https://github.com/KevinDockx/RESTfulAPIAspNetCore_Course/pull/5

**Comment by KevinDockx** [comment]
Thanks @willvelida !
